name: test
on: [push, pull_request]
permissions: read-all
jobs:
  unittest:
    name: unittest
    runs-on: ubuntu-latest
    steps:
      # checkout source code
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      # install dependencies
      - run: pip install -r requirements.txt

      # install pytest-cov
      - run: pip install pytest-cov

      # run unittest and covertest
      - run: pytest -v --cov=.
      
  
